### ISSUE TITLE
Servers don't load

### ISSUE THREAD

**Issue by Ironbrodiet** [PrecisionClient/PrecisionClient#17]
I think it's just me but servers don't load for me most of the time. This is the same for me for resent client.

**Comment by Ironbrodiet** [comment]
![Screenshot 2022-11-16 7 55 52 AM](https://user-images.githubusercontent.com/95990226/202229995-3228d7b4-f49b-410f-b21f-9bb08f712448.png)

**Comment by Ironbrodiet** [comment]
I am using a proxy in the photo.

**Comment by ninefivenine** [comment]
https://holyubofficial.net/1.html

**Comment by Ironbrodiet** [comment]
I'm going to close the issue because it doesn't exactly have much to do with the client itself.

**Comment by etcherfx** [comment]
use titanium network's ultraviolet
