### ISSUE TITLE
How do you play this as a offline download?

### ISSUE THREAD

**Issue by Ironbrodiet** [PrecisionClient/PrecisionClient#7]
The Eaglercraft GitHub has an offline download, but from what I know this doesn't. If there isn't, please make one. If there already is and I'm blind, please tell me. Thanks!

**Comment by etcherfx** [comment]
there is no offline downloads for the new version yet but you can download older offline downloads from the PrecisionClient.old repository

**Comment by Ironbrodiet** [comment]
yeah

**Comment by Ironbrodiet** [comment]
Shall I close the issue?

**Comment by Willydaham09** [comment]
> Shall I close the issue?

Ye

**Comment by etcherfx** [comment]
I've decided that offline downloads will no longer be supported because it is too laggy (won't load) with the texture packs and singleplayer

**Comment by Ironbrodiet** [comment]
Okay, thanks for letting me know.
