### ISSUE TITLE
elhp pause screen!11!!!1

### ISSUE THREAD

**Issue by ThisIsALegitUsername** [PrecisionClient/PrecisionClient#9]
so liek wen i clik on ark.io buton and clos it i acnt get out of pauze screen plz fix ty

**Comment by ThisIsALegitUsername** [comment]
i sink its bcuz i hav scool kromebooka and the scool bloked percsun clinet!!11!1

**Comment by Guzhini** [comment]
https://user-images.githubusercontent.com/90022305/200151780-8a9967ae-9347-473d-aed5-bd8441f11c47.mp4

i guess the nitwit is a nitwit

**Comment by ThisIsALegitUsername** [comment]
LMAO since when did someone make a full 2:38 minute length video???

**Comment by etcherfx** [comment]
please refrain from creating duplicate issues or non-serious issues.
